services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mock-api:
    build:
      context: ./packages/mock-api
    ports:
      - "3001:3001"
    environment:
      PORT: "3001"

  proxy:
    build:
      context: ./packages/proxy
    ports:
      - "3000:3000"
    depends_on:
      - mock-api
      - redis
    environment:
      PORT: "3000"
      UPSTREAM_HOST: "http://mock-api:3001"
      REDIS_URL: "redis://redis:6379"

  mapstore:
    image: geosolutionsit/mapstore2
    ports:
      - "8080:8080"
    depends_on:
      - proxy
